version: "3.9"

services:
#  app:
#    build: ./
#    command: ./app
#    depends_on:
#     - kafka
#    volumes:
#      - ../:./

  zookeeper:
    image: bitnami/zookeeper:3.8.1
    networks:
      - app
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.4.0
    volumes:
      - kafka:/bitnami/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"

volumes:
  kafka:
    driver: local

networks:
  app:
    driver: bridge